name: Cron
on:
  schedule:
  - cron: "0 0 * * *"
jobs:
  build:
    name: cron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: mstksg/get-package@v1
        with:
                apt-get: make expat libopenscap8 libxml2-utils ninja-build python3-jinja2 python3-yaml xsltproc
      - name: Make
        run: |
          make clean all
      - name: Push to master
        uses: mikeal/publish-to-github-action@master
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
